apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamodb-service-sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dynamodb-service-sample
  template:
    metadata:
      labels:
        app: dynamodb-service-sample
    spec:
      containers:
      - name: api
        image: ${DOCKER_REGISTRY_URL}/kenmu/dynamodb-service-sample@${DOCKER_IMAGE_DIGEST}
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: "64Mi"
            cpu: "100m"
